/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cora.app;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import cora.lib.exceptions.ParserException;
import cora.lib.terms.Term;
import cora.lib.rewriting.TRS;
import cora.lib.parsers.CoraInputReader;
import cora.lib.parsers.TrsInputReader;

public class App {
  private static String getExtension(String filename) {
    int i = filename.lastIndexOf('.');
    if (i >= 0) return filename.substring(i+1);
    return "";
  }

  private static TRS readInput(String file) throws Exception {
    String extension = getExtension(file);
    if (extension.equals("trs") || extension.equals("mstrs")) {
      return TrsInputReader.readTrsFromFile(file);
    }
    if (extension.equals("cora")) {
      return CoraInputReader.readProgramFromFile(file);
    }
    throw new Exception("Unknown file extension: " + extension + ".");
  }

  public static void main(String[] args) {
    try {
      TRS trs = args.length > 0 ? readInput(args[0]) : readInput("file_examples/test.cora");
      if (trs == null) return;

      System.out.print(trs.toString());
      System.out.print("Input term: ");
      String input = (new BufferedReader(new InputStreamReader(System.in))).readLine();
      Term term = CoraInputReader.readTermFromString(input, trs, null);
      do {
        term = trs.leftmostInnermostReduce(term);
        if (term != null) System.out.println("⇒ " + term.toString());
      } while (term != null);
    }
    catch (Exception e) {
      System.out.println("Exception: " + e.getMessage());
    }
  }
}
