/**************************************************************************************************
 Copyright 2019 Cynthia Kop

 Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software distributed under the
 License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 express or implied.
 See the License for the specific language governing permissions and limitations under the License.
 *************************************************************************************************/

package cora.lib.exceptions;

import java.util.ArrayList;

/**
 * An AntlrParserException is a collection of error messages generated by lexing or parsing ome
 * user input into a parse tree.
 */
public class AntlrParserException extends ParserException {
  private int _errorCount;

  private static String collectErrors(ArrayList<String> messages) {
    String str = "";
    for (int i = 0; i < messages.size() && i < 10; i++) {
      str += messages.get(i) + "\n";
    }
    if (messages.size() > 10) str += "[Truncated; " + messages.size() + " more.]";
    return str;
  }

  public AntlrParserException(ArrayList<String> messages) {
    super(null, collectErrors(messages));
    _errorCount = messages.size();
  }

  public int getTotalErrorCount() {
    return _errorCount;
  }
}

